[theme]
primaryColor = "#b22222"               # firebrick (merah matang)
backgroundColor = "#cbe6b6"           # putih bersih
secondaryBackgroundColor = "#85c799"   # hijau muda lebih pekat
textColor = "#2e2e2e"                 # abu tua, kontras
font = "sans serif"
